import React, { useState } from 'react';
import { Card } from '../../components/ui/Card';
import { Input } from '../../components/ui/Input';
import { Button } from '../../components/ui/Button';
import { Send, Bot } from 'lucide-react';

export const QueryInput = () => {
    const [query, setQuery] = useState('');
    const [response, setResponse] = useState(null);
    const [loading, setLoading] = useState(false);

    const handleQuery = (e) => {
        e.preventDefault();
        if (!query.trim()) return;

        setLoading(true);
        // Simulate API delay
        setTimeout(() => {
            setResponse({
                type: 'analysis',
                text: `Analysis for: "${query}"`,
                data: 'Based on the current data patterns, students are performing 15% better in practical subjects compared to theoretical assessments.'
            });
            setLoading(false);
        }, 1500);
    };

    return (
        <div className="space-y-6 max-w-4xl mx-auto">
            <div className="text-center space-y-2">
                <h2 className="text-3xl font-bold tracking-tight">AI Analysis Query</h2>
                <p className="text-gray-500">Ask questions about student performance, trends, or specific data points.</p>
            </div>

            <Card className="p-6">
                <form onSubmit={handleQuery} className="flex gap-4">
                    <Input
                        placeholder="e.g., 'Show me the correlation between attendance and math scores'"
                        value={query}
                        onChange={(e) => setQuery(e.target.value)}
                        className="flex-1"
                    />
                    <Button type="submit" disabled={loading || !query}>
                        {loading ? 'Analyzing...' : <><Send className="mr-2 h-4 w-4" /> Ask AI</>}
                    </Button>
                </form>
            </Card>

            {response && (
                <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
                    <Card className="border-indigo-100 bg-indigo-50/50">
                        <div className="flex gap-4">
                            <div className="mt-1 h-8 w-8 rounded-full bg-indigo-600 flex items-center justify-center text-white shrink-0">
                                <Bot className="h-5 w-5" />
                            </div>
                            <div className="space-y-2">
                                <h4 className="font-semibold text-indigo-900">Analysis Result</h4>
                                <p className="text-indigo-800 leading-relaxed">
                                    {response.data}
                                </p>
                                <div className="mt-4 p-4 bg-white rounded-lg border border-indigo-100 text-sm text-gray-500 italic">
                                    "This is a mocked response. In a real system, this would be generated by an LLM or specific data query backend."
                                </div>
                            </div>
                        </div>
                    </Card>
                </div>
            )}
        </div>
    );
};
